# -*- coding: utf-8 -*-
"""IDS_20200522_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z9EzIVlElC6uFPCWpgabpKeo0V6kkggD
"""

years = [2012, 2015, 2018, 2019]
for year, movie in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))