# -*- coding: utf-8 -*-
"""IDS_20200327_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EYxGdEbxxR6YOTrQd7lOSe1JzyxK4duY
"""

current_celsius = 28
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)

shaq_height = 216
shaq_weight = 147
shaq_bmi = shaq_weight / (shaq_height/100)**2
print(shaq_bmi)

ross_said = "Let's put aside the fact that you \"accidentally\" pick up my grandmother's ring."
print(ross_said)

city = input("請輸入你在的城市:")
weather = input("請輸入目前的天氣")
print("我在{}，天氣{}".format(city,weather))

print(type(True))
print(type(False))

shaq_bmi = 31.507201646090532
print(shaq_bmi > 30)