# -*- coding: utf-8 -*-
"""Week3作業.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_DESxfMLlK0RvxEmH4uoCpddmf3RDxo
"""

print = 5566
del print

movie_title = "Avengers: Endgame"
print(movie_title)

help(abs)

help(all)

help(print)

help(help)

my_object = 5566
print(my_object)

my_str = '5566'
print(my_str)

movie_titile = "Avengers: Endgame"
 movie_time = 181
 movie_rating = 8.4

 print(movie_title)
 print(movie_time)
 print(movie_rating)

 print(type(movie_title))
 print(type(movie_time))
 print(type(movie_rating))

