# -*- coding: utf-8 -*-
"""Copy of Week3作業.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ydJn5_7BQlvP1f8dUZ96ZUPoCFUgqxp
"""

movie_titile = "Avengers: Endgame"
 movie_time = 181
 movie_rating = 8.4

 print(movie_title)
 print(movie_time)
 print(movie_rating)

 print(type(movie_title))
 print(type(movie_time))
 print(type(movie_rating))

