# -*- coding: utf-8 -*-
"""Week2-A107260076-蕭伯勳.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vubJYg0yWK7NYK-iyMUfHrQCEa7Oewk7
"""

print("Hello World!")

import this