# -*- coding: utf-8 -*-
"""IDS_20200508_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ZoKEhmB96aCPkI4TKQqbgppbYxOjorX
"""

i = 0
while i < len(cast_list_a):
    actor = cast_list_a[i].get('alt').strip()
    cast.append(actor)
    i += 1