# -*- coding: utf-8 -*-
"""IDS_20200508_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vfnOqzqdHuhqTxQsT2t9OdMi8Y0VB2Wf
"""

!pip install -U beautifulsoup4