# -*- coding: utf-8 -*-
"""IDS_20200508_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYHT4Tjyg5rmplDPei_yyj7yupV6kXAT
"""

actor_1 = cast_list_a[1].get('alt').strip()
cast_list.append(actor_1)
print(cast_list)