# -*- coding: utf-8 -*-
"""IDS_20200508_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16b0kzJfzccthgyAd_7vmjqgof0oV9fqI
"""

print(cast)