# -*- coding: utf-8 -*-
"""IDS_20200508_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0c_0MDCcw5TDgi2qBcufK6NvWx2WJAH
"""

print(cast[8])
print(cast[-7])