# -*- coding: utf-8 -*-
"""IDS_20200508_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Otn30SjSpO3nFjA5BRxB2TWPJDezmWnV
"""

cast_list = []
print(cast_list)
print(type(cast_list))
print(len(cast_list))