# -*- coding: utf-8 -*-
"""IDS_20200508_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7yvkMbhTY6wNQozuQRwbv8y_qEfm67U
"""

import requests
from bs4 import BeautifulSoup

response = requests.get('https://www.imdb.com/title/tt4154796/')
soup = BeautifulSoup(response.text)