# -*- coding: utf-8 -*-
"""IDS_20200508_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYktA6tqKNLLLzcwQor2D7me4H56wIZP
"""

cast = []
print(cast)
print(type(cast))
print(len(cast))