# -*- coding: utf-8 -*-
"""IDS_20200508_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DxY-VpT5D9vWlw0dSSdj0TPOnqpQSORm
"""

print(len(cast))
print(cast[:6])