# -*- coding: utf-8 -*-
"""IDS_20200508_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIj5N86BROTTCC4T0ofgPsneGQe9siTA
"""

actor_0 = cast_list_a[0].get('alt').strip()
cast_list.append(actor_0)
print(cast_list)