# -*- coding: utf-8 -*-
"""IDS_20200508_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bXtoEf62yI-4tzREP-DBacYOPGlhuMKI
"""

cast_list_a = soup.select("#titleCast .loadlate")
print(len(cast_list_a))