# -*- coding: utf-8 -*-
"""Copy of Copy of IDS_20200327_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1koHNeYVrNM1SPkZmHMsVTs-43-m0QPGJ
"""

city = input("請輸入你在的城市:")
weather = input("請輸入目前的天氣")
print("我在{}，天氣{}".format(city,weather))