# -*- coding: utf-8 -*-
"""Copy of IDS_20200327_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AbaONMrOf3TFaFO9r9kq20ormGSYQkzI
"""

ross_said = "Let's put aside the fact that you \"accidentally\" pick up my grandmother's ring."
print(ross_said)