# -*- coding: utf-8 -*-
"""Copy of IDS_20200327_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcdnFk1kykkHkCvZRoSIEz23LcmWEFwg
"""

shaq_height = 216
shaq_weight = 147
shaq_bmi = shaq_weight / (shaq_height/100)**2
print(shaq_bmi)