# -*- coding: utf-8 -*-
"""IDS_20200327_1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EYxGdEbxxR6YOTrQd7lOSe1JzyxK4duY
"""

current_celsius = 28
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)