# -*- coding: utf-8 -*-
"""Copy of IDS_20200327_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDh7JavCYYDVx8H_QTdUEgXUHv3X8gm_
"""

print(type(True))
print(type(False))
shaq_bmi = 31.507201646090532
print(shaq_bmi > 30)