# -*- coding: utf-8 -*-
"""Copy of IDS_20200410_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mPHU3N1hl_Jm4WGxCeF8vkasc8vfAo1R
"""

print(ans)