# -*- coding: utf-8 -*-
"""Copy of IDS_20200410_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSBnRtn-KNxyedsNSMpAtsaJY0ouyAuM
"""

id_last_digit = input("請輸入您身分證字號的尾數")