# -*- coding: utf-8 -*-
"""Copy of IDS_20200410_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-UOBU5u_WfsbsSzX4vqrTMnIUy1RoGO
"""

ans = int(id_last_digit) % 2 == 1