# -*- coding: utf-8 -*-
"""IDS_20200529_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMWXG7Pq1Nws_c7jJWUW9_glycR08-3l
"""

is_prime(1)