# -*- coding: utf-8 -*-
"""IDS_20200529_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/109TN5jTHL4j4SC1wfTLpQyRD_9rMK5XS
"""

sample_history = []
while True:
    random_integer = sample(range(1, 1001), 1)[0]
    sample_history.append(random_integer)
    if random_integer % 56 == 0:
        break
print(sample_history)
print(len(sample_history))