# -*- coding: utf-8 -*-
"""IDS_20200529_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rUdtGsOuik05Z-GRfgDXOjee7RUGhxnA
"""

n_vowels = 0 
for i in 'azcbobobegghak':
    if i in ['a', 'e', 'i', 'o', 'u']:
        #print(i)
        n_vowels += 1
print(n_vowels)