# -*- coding: utf-8 -*-
"""IDS_20200529_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QRhakHxB6J1oht4-k6znCvbjwZlBMQbc
"""

is_prime(8)