# -*- coding: utf-8 -*-
"""IDS_20200529_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zFVdqoZ0lQs7DzfgkNhtwCULFsJVI9Zc
"""

from statistics import stdev

stdev(range(1, 101)) # [1, 2, 3, ..., 100]