# -*- coding: utf-8 -*-
"""IDS_20200529_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XNR-NZ4HdxWehmVRNiSBhC__PRRg-uT
"""

def get_fahrenheit(x):
    """
    Transform a Celsius degree into  Farenheit scale
    """
    fah = x * 9/5 + 32
    return fah