# -*- coding: utf-8 -*-
"""IDS_20200529_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbrSZD5DdKNR20VKf8ykASq1VoLgTIsx
"""

is_prime(2)