# -*- coding: utf-8 -*-
"""IDS_20200529_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dhepKtnOiPFlfJ5SPUpgGTN2ZYB_VpGF
"""

get_bmi(216, 147)