# -*- coding: utf-8 -*-
"""IDS_20200529_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zm6bDGyLyLCNQYNvW27uu__3X1R1J_M2
"""

def get_bmi(height, weight):
    """
    Calculate BMI based on height and weight
    """
    height = height / 100
    bmi = weight / height**2
    return bmi