# -*- coding: utf-8 -*-
"""IDS_20200529_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s2Pr4Iu7MHnW5yk0NXneh-c4chYMLaD0
"""

get_fahrenheit(32)