# -*- coding: utf-8 -*-
"""IDS_20200529_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rq-NBDyHdhblOuWTAT2OsHND2Kyu5Iir
"""

get_bmi(198, 129)