# -*- coding: utf-8 -*-
"""IDS_20200515_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CfPNgycFmJ8skZ-e-NSJfdbpulYv3dH1
"""

primes_list = [2, 3, 5, 7, 11]
primes_list[-1] = 13 # update
print(primes_list)

primes_list.insert(-1, 11) # increase length
print(primes_list)

primes_list.pop()
print(primes_list)