# -*- coding: utf-8 -*-
"""IDS_20200515_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_uzQx5UH0piDQ1bdD0gElDfEKdPCbND
"""

def where_are_you_from(city, country):
    return city, country

print(where_are_you_from("Taipei", "Taiwan"))
print(type(where_are_you_from("Taipei", "Taiwan")))