# -*- coding: utf-8 -*-
"""IDS_20200515_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1itXktHUnwaHK-7ioSQUL_LIov7n8CjZX
"""

my_city, my_country = where_are_you_from("Taipei", "Taiwan")
print(my_city)
print(my_country)