# -*- coding: utf-8 -*-
"""IDS_20200515_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ppINdHvVopxaQ5kAY5Bbj2BGdYDVodti
"""

the_avengers = {
    "Iron Man": "Tony Stark",
    "Captain America": "Steve Rogers",
    "Hulk": "Bruce Banner",
    "Thor": "Thor",
    "Black Widow": "Natasha Romanoff",
    "Hawkeye": "Clint Barton"
}
print(the_avengers)
print(type(the_avengers))
print("------------------------------")

print(the_avengers.keys())
print(the_avengers.values())
print(the_avengers.items())