# -*- coding: utf-8 -*-
"""IDS_20200515_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtQU4Gv4O82mCkPswuqj1sCpoStdQKAs
"""

primes = {2, 3, 5, 7, 11, 13}
print(primes)
print(type(primes))

primes_list = [2, 3, 3, 3, 5, 5]
print(primes_list)

print(set(primes_list))

primes = {2, 3, 5, 7, 11, 13, 13, 13, 11, 11, 11, 11, 2, 2, 2}
print(primes)