# -*- coding: utf-8 -*-
"""IDS_20200515_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_I4GzkbarHB08j7Pw9grBZnmpkQV2KD
"""

x = 0.25
print(type(x))
print(x.as_integer_ratio())
print(type(x.as_integer_ratio()))

numerator, denominator = x.as_integer_ratio()
print(numerator)
print(denominator)