# -*- coding: utf-8 -*-
"""IDS_20200515_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xM-_1Z31iBKn3VuzzH5cA1LJ_jzybt5P
"""

primes = (2, 3, 5, 7, 11)
print(type(primes))