# -*- coding: utf-8 -*-
"""IDS_20200501_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bh7Wa0chOUIpwPz8K_Yp07MxTpl2EfE8
"""

x = int(input("請輸入起始的整數:")) 
y = int(input("請輸入終止的整數:"))
i = x # start
while i <= y: # stop
    # task
    if i % 2 == 1:
      print(i)
    i += 1 # step