# -*- coding: utf-8 -*-
"""IDS_20200417_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XCLcZR9I9Cuq0BWJ8dBYDD-IAQ4-j4qo
"""

id_last_digit = input("請輸入您身分證字號的尾數:")
id_last_digit = int(id_last_digit)
if id_last_digit % 2 == 1:
    ans = "星期一三五日領"
if id_last_digit % 2 == 0:
    ans = "星期二四六領"
print(ans)