# -*- coding: utf-8 -*-
"""IDS_20200417_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vl6JYwpt2eOj5uqcgwatBg3_sRwYC4DY
"""

user_int = input("請輸入一個正整數：")
user_int = int(user_int)
if user_int % 2 == 0:
    ans = "偶數"
if user_int % 2 == 1:
    ans = "奇數"
print(ans)