# -*- coding: utf-8 -*-
"""IDS_20200417_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tm7YdMw4aAI49ViBldjqdFDvG3wQSfND
"""

user_int = input("請輸入一個正整數：")
user_int = int(user_int)
if user_int % 2 == 0:
    ans = "偶數"
if user_int % 2 == 1:
    ans = "奇數"
print(ans)